### ISSUE TITLE
yalan

### ISSUE THREAD

**Issue by greatfucker89** [DeepWebTurkiye/Deep-Web-Turkce-Siteler#1]
verilen linklerin yarısı ölü diğer yarısı da hep aynı siteye yönlendiriyor. silkyroad 2013'te kapatıldı ama burada silkyroad tr adıyla bir fishing sitesi kurulmuş, sitede yer alan yorumlara kadar herşey tek kişi tarafından hazırlanmış herşey düşünülmüş tamamen dolandırma amaçlı. oltaya takılıp paranızı kaptırmayın.

**Comment by Falconpaw** [comment]
@greatfucker89 doğru söylüyor 1000$ kaptırdım Tulpar T7 Siparişi verdim hesabı kapattılar olay örgüsünü aşağıya yazıyorum.

### **Araştırma**

Sitede çok gezdim çok iyi ürünler olduğunu gördüm daha sonra aklımda olan soruları sipariş geçeceğim satıcıyla birebir konuştum sorularım yanıtlandı.

### **Sipariş**
Playstation 4 Pro siparişi verdim. Siparişi verdiğimde adam siparişi hazırlıyorum diye mesaj attı. Para escrowa düşmüştü. Daha sonra bir mesaj daha yolladı mesajda ps4'ün kırık olduğu siparişi gönderdiğinde escrow'a söylesede iptal olacağını o yüzden siparişi iptal ettiğini söyledi. 200 $ lık siparişti yaklaşık 0.02 BTC yatırmıştım. Bende durumu sürüklememek adına parayı tekrar kendi btc hesabıma geçmeye çalıştığımda bir uyarı aldım. Uyarıda 0.05 btc çekebilirsiniz ibaresi yer alıyodu. Bunu çekebilmek için 0.05 Btc ye tamamlamak yerine 0.16 btc yatırarak yakşalık 1000$ değerinde Tulpar T7 sipariş vermeye karar verdim. Parayı yatırdım ve Siparişi geçtim. Anlık escrow BTC hesabı oluşturma yöntemi yapılmış ve geçilen btcler hesabıma geçmişti. 
Siparişi verdiğim anda para escrow'a düştü.

### **Farkına Varış**

Gece siparişi geçmiştim. Sabah kullanıcı adım ve şifremle girmeye çalıştığımda bu şekllde hata aldım. https://prnt.sc/rfyya0

Daha sonra kullanıcı adımı yanlış giriyorum diye yanlış kullanıcı adı girerek şifremi girdim ve normal uyarının yanında farklı bir ibare gördüm. Burada anladım ki hesabım askıya alınmış.

Yeni kullanıcı açıp adminlere mesaj attım. Satıcıya mesaj attım o kadar çok geç dönülüyodu ki anladığımda bir kişinin tüm kullanıcıları tek tek dolaşıp müşterilere cevap yazdığını kafamda anladım. Artık geri dönüşü olmayan bir yolda 1000$ dolandırıldığımı anladım ve kolay yoldan iyi bir ürüne sahip olmak isterken böyle bişey olmayacağını daha iyi anladım. 



### **İNANMAYIN!**

**Comment by komunation** [comment]
@Falconpaw hocam bahsettiğin marketin ismi dream tr diye değişmiş sanırım ama emin olamadım. sizi dolandıran kişiler değil mi bunlar da

**Comment by Falconpaw** [comment]
@komunation aynen dostum.

**Comment by huger1** [comment]
BEYLER MERHABA DEEB WEBTR FORUM İLE WORLD MARKET TR BİRLİKTE ÇALIŞIYOR FORUMDA MARKETİN GÜZELLEMESİNİ YAPIP MİLLETİ YEMLİYORLAR SONRADA HESABI KAPATIYORLAR ARKADAŞIN BAŞINA GELEN OLAYIN AYNISI BANADA GELDİ 350 DOLAR KAPTIRDIM SAKIN YAPMAYIN YANMAYIN
