### ISSUE TITLE
Torrez Market Dolandırıcı %100 SCAM

### ISSUE THREAD

**Issue by selim995** [DeepWebTurkiye/Deep-Web-Turkce-Siteler#18]
Türkçe deep web market http://qldzeqhdx2kgem33mw7tpqeg45slurikjxvv6j2es7fclmlz4ghhh3yd.onion  üzerinden bir arkadaş 380 dolarlık alışveriş yaptı ve hesabını kapattılar. Bu markette dolandırıcı scam.

**Comment by DanielBryan0** [comment]
Torrez Market Türk dolandırıcı marketlerinden biridir sitelerinin isimlerini birçok kez deşiğiştirmişlerdir. (Eski adları: Neptune Market, Dream Market tr, World Market tr, Silkroad tr... Ve şu an marketin ismi Torrez olarak değiştirilmiştir.)
Kendileri insanları dolandırmakta bir numaradır. Sırf İnsanları dolandırmak için Forum ve İndex açmışlardır. Forumda Torrez (Adı habire değişiyor ama sitenin arayüzü hep aynı) Marketi övmek için fake hesaplar açmışlardır. Dolandırldığını Söyleyen kişinin postu silinir ve ban yer. Sitede Alışveriş yaparsanız hesabınız silinir Ve paranız gider. Benim yazım dışında başka kaynaklar:
Forum ile ilgili https://eksisozluk.com/deeptr--6928153
Marketin Dolandırıcığı ile ilgili https://www.turkhackteam.org/konular/deeptr-neptune-market-dolandiriciligi.1989516/

https://eksisozluk.com/world-market-tr--6928162
Paranızı Dolandırıcılara vericeğinize Allah yolunda Harcayın.
