### ISSUE TITLE
İNANMAYIN!!!

### ISSUE THREAD

**Issue by Falconpaw** [DeepWebTurkiye/Deep-Web-Turkce-Siteler#3]
@greatfucker89 doğru söylüyor 1000$ kaptırdım Tulpar T7 Siparişi verdim hesabı kapattılar olay örgüsünü aşağıya yazıyorum.

Araştırma
Sitede çok gezdim çok iyi ürünler olduğunu gördüm daha sonra aklımda olan soruları sipariş geçeceğim satıcıyla birebir konuştum sorularım yanıtlandı.

Sipariş
Playstation 4 Pro siparişi verdim. Siparişi verdiğimde adam siparişi hazırlıyorum diye mesaj attı. Para escrowa düşmüştü. Daha sonra bir mesaj daha yolladı mesajda ps4'ün kırık olduğu siparişi gönderdiğinde escrow'a söylesede iptal olacağını o yüzden siparişi iptal ettiğini söyledi. 200 $ lık siparişti yaklaşık 0.02 BTC yatırmıştım. Bende durumu sürüklememek adına parayı tekrar kendi btc hesabıma geçmeye çalıştığımda bir uyarı aldım. Uyarıda 0.05 btc çekebilirsiniz ibaresi yer alıyodu. Bunu çekebilmek için 0.05 Btc ye tamamlamak yerine 0.16 btc yatırarak yakşalık 1000$ değerinde Tulpar T7 sipariş vermeye karar verdim. Parayı yatırdım ve Siparişi geçtim. Anlık escrow BTC hesabı oluşturma yöntemi yapılmış ve geçilen btcler hesabıma geçmişti.
Siparişi verdiğim anda para escrow'a düştü.

Farkına Varış
Gece siparişi geçmiştim. Sabah kullanıcı adım ve şifremle girmeye çalıştığımda bu şekllde hata aldım. https://prnt.sc/rfyya0

Daha sonra kullanıcı adımı yanlış giriyorum diye yanlış kullanıcı adı girerek şifremi girdim ve normal uyarının yanında farklı bir ibare gördüm. Burada anladım ki hesabım askıya alınmış.

Yeni kullanıcı açıp adminlere mesaj attım. Satıcıya mesaj attım o kadar çok geç dönülüyodu ki anladığımda bir kişinin tüm kullanıcıları tek tek dolaşıp müşterilere cevap yazdığını kafamda anladım. Artık geri dönüşü olmayan bir yolda 1000$ dolandırıldığımı anladım ve kolay yoldan iyi bir ürüne sahip olmak isterken böyle bişey olmayacağını daha iyi anladım.

İNANMAYIN!

**Comment by komunation** [comment]
> @greatfucker89 doğru söylüyor 1000$ kaptırdım Tulpar T7 Siparişi verdim hesabı kapattılar olay örgüsünü aşağıya yazıyorum.
> 
> Araştırma
> Sitede çok gezdim çok iyi ürünler olduğunu gördüm daha sonra aklımda olan soruları sipariş geçeceğim satıcıyla birebir konuştum sorularım yanıtlandı.
> 
> Sipariş
> Playstation 4 Pro siparişi verdim. Siparişi verdiğimde adam siparişi hazırlıyorum diye mesaj attı. Para escrowa düşmüştü. Daha sonra bir mesaj daha yolladı mesajda ps4'ün kırık olduğu siparişi gönderdiğinde escrow'a söylesede iptal olacağını o yüzden siparişi iptal ettiğini söyledi. 200 $ lık siparişti yaklaşık 0.02 BTC yatırmıştım. Bende durumu sürüklememek adına parayı tekrar kendi btc hesabıma geçmeye çalıştığımda bir uyarı aldım. Uyarıda 0.05 btc çekebilirsiniz ibaresi yer alıyodu. Bunu çekebilmek için 0.05 Btc ye tamamlamak yerine 0.16 btc yatırarak yakşalık 1000$ değerinde Tulpar T7 sipariş vermeye karar verdim. Parayı yatırdım ve Siparişi geçtim. Anlık escrow BTC hesabı oluşturma yöntemi yapılmış ve geçilen btcler hesabıma geçmişti.
> Siparişi verdiğim anda para escrow'a düştü.
> 
> Farkına Varış
> Gece siparişi geçmiştim. Sabah kullanıcı adım ve şifremle girmeye çalıştığımda bu şekllde hata aldım. https://prnt.sc/rfyya0
> 
> Daha sonra kullanıcı adımı yanlış giriyorum diye yanlış kullanıcı adı girerek şifremi girdim ve normal uyarının yanında farklı bir ibare gördüm. Burada anladım ki hesabım askıya alınmış.
> 
> Yeni kullanıcı açıp adminlere mesaj attım. Satıcıya mesaj attım o kadar çok geç dönülüyodu ki anladığımda bir kişinin tüm kullanıcıları tek tek dolaşıp müşterilere cevap yazdığını kafamda anladım. Artık geri dönüşü olmayan bir yolda 1000$ dolandırıldığımı anladım ve kolay yoldan iyi bir ürüne sahip olmak isterken böyle bişey olmayacağını daha iyi anladım.
> 
> İNANMAYIN!

hocam bahsettiğiniz sitenin ismi şuan dream tr olmuş sanırsam hala aynı dolandırıcı site mi? yoksa farklı siteler mi

**Comment by greatfucker89** [comment]
> 
> 
> > @greatfucker89 doğru söylüyor 1000$ kaptırdım Tulpar T7 Siparişi verdim hesabı kapattılar olay örgüsünü aşağıya yazıyorum.
> > Araştırma
> > Sitede çok gezdim çok iyi ürünler olduğunu gördüm daha sonra aklımda olan soruları sipariş geçeceğim satıcıyla birebir konuştum sorularım yanıtlandı.
> > Sipariş
> > Playstation 4 Pro siparişi verdim. Siparişi verdiğimde adam siparişi hazırlıyorum diye mesaj attı. Para escrowa düşmüştü. Daha sonra bir mesaj daha yolladı mesajda ps4'ün kırık olduğu siparişi gönderdiğinde escrow'a söylesede iptal olacağını o yüzden siparişi iptal ettiğini söyledi. 200 $ lık siparişti yaklaşık 0.02 BTC yatırmıştım. Bende durumu sürüklememek adına parayı tekrar kendi btc hesabıma geçmeye çalıştığımda bir uyarı aldım. Uyarıda 0.05 btc çekebilirsiniz ibaresi yer alıyodu. Bunu çekebilmek için 0.05 Btc ye tamamlamak yerine 0.16 btc yatırarak yakşalık 1000$ değerinde Tulpar T7 sipariş vermeye karar verdim. Parayı yatırdım ve Siparişi geçtim. Anlık escrow BTC hesabı oluşturma yöntemi yapılmış ve geçilen btcler hesabıma geçmişti.
> > Siparişi verdiğim anda para escrow'a düştü.
> > Farkına Varış
> > Gece siparişi geçmiştim. Sabah kullanıcı adım ve şifremle girmeye çalıştığımda bu şekllde hata aldım. https://prnt.sc/rfyya0
> > Daha sonra kullanıcı adımı yanlış giriyorum diye yanlış kullanıcı adı girerek şifremi girdim ve normal uyarının yanında farklı bir ibare gördüm. Burada anladım ki hesabım askıya alınmış.
> > Yeni kullanıcı açıp adminlere mesaj attım. Satıcıya mesaj attım o kadar çok geç dönülüyodu ki anladığımda bir kişinin tüm kullanıcıları tek tek dolaşıp müşterilere cevap yazdığını kafamda anladım. Artık geri dönüşü olmayan bir yolda 1000$ dolandırıldığımı anladım ve kolay yoldan iyi bir ürüne sahip olmak isterken böyle bişey olmayacağını daha iyi anladım.
> > İNANMAYIN!
> 
> @Falconpaw hocam bahsettiğiniz sitenin ismi şuan dream tr olmuş sanırsam hala aynı dolandırıcı site mi? yoksa farklı siteler mi

aynı site. dolandırıcı kişi işinin ehli dostum sitenin adını değiştirmiş. yarın da samsara tr yapar. sitedeki bütün içerikler tek kişi tarafından hazırlanmış. ben para kaptırmadım ama yukarıdaki arkadaş kaptırmış bak dikkat edin.

**Comment by Falconpaw** [comment]
@komunation Evet dostum aynı site. Kesinlikle alışveriş yapmayın 1000$ım gitti en zor zamanda iş için alıcaktım Tulparı nerden bulabilirsin ki öyle şeyleri Tr de.

**Comment by Bygizemli-tech** [comment]
http://tdwturk7wp4qt3feeimkeymidxnxqccnzziwlbe2driw2potlixjk2ad.onion

Hocam burası güvenilir alışveriş yaptım

**Comment by Bygizemli-tech** [comment]
http://tdwturk7wp4qt3feeimkeymidxnxqccnzziwlbe2driw2potlixjk2ad.onion

Hocam burası güvenilir alışveriş yaptım

**Comment by Bayyn** [comment]
Issuesleri okumadığıma bu kadar pişman olamazdım. DeepTR'yi yapanda kendisi büyük ihtimal kendisi çünkü orda alışveriş yaptım yazıyordu. Bende 300$ dolandırıldım. Kaynak kodlara baktığım kadarıyla adam cidden işinin ehli, baya baya c2c sistemi yazıp üşenmeden o kadar içerik yorum girmiş. Ben de kandım siz kanmayın.

**Comment by mk0666** [comment]
Yeni adı hydra market diye geçiyor evet tam bir dolandırıcı sitesi herşeyi yalan sakın alışveriş yapmayın bende dolandırıldım 400 tl civarı bir param gitti eski adı dream marketti sitenin

**Comment by lilcsz** [comment]
deep webten ürün alıcak kadar aptal mısınız

**Comment by mk0666** [comment]
Senin kadar aptal değiliz

27 Eyl 2020 Paz 02:50 tarihinde lilcsz ***@***.***> şunu
yazdı:
