### ISSUE TITLE
Deepweb Türk Forum Sitesi

### ISSUE THREAD

**Issue by Bygizemli-tech** [DeepWebTurkiye/Deep-Web-Turkce-Siteler#7]
http://tdwturk7wp4qt3feeimkeymidxnxqccnzziwlbe2driw2potlixjk2ad.onion

**Comment by mk0666** [comment]
Escrowtra4utbzsi.onion uzantısı içindeki hydra market denen yer dolandırıcıdır herşeyi sahtedir aldanmayın sakın paranızı kaptırmayın

**Comment by liberty26** [comment]
eski adı hydra olan yeni adıysa worldmarkettr xprqjjnon7ryev3qs3ctjnj6f37wvgmnlp4oawwztzdb5aldawjpkmqd.onion uzantılı velet tokatcıdır en büyük sahtekardır türkiye'de bir numaradır bütün ürünler sahte ve tokat
